title: Frank Sitawa
description: Technology, Travel, Food & Life
url: "http://localhost:4000"
baseurl: ""

sass:
  sass_dir: _sass
  style: compressed
collections:
  authors:
    output: true
  portfolio:
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: ""
    values:
      layout: "default"